.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.40.6.
.TH FS_MARK: "1" "March 2012" "fs_mark: invalid option -- '-'" "User Commands"
.SH NAME
fs_mark: \- manual page for fs_mark: invalid option -- '-'
.SH SYNOPSIS
.B fs_mark

.SH DESCRIPTION
fs_mark: invalid option \fB\-\-\fR '\-'
.HP
\fB\-h\fR <print usage and exit>
.HP
\fB\-k\fR <keep files after each iteration>
.HP
\fB\-F\fR <run until FS full>
.HP
\fB\-S\fR Sync Method (0:No Sync, 1:fsyncBeforeClose, 2:sync/1_fsync, 3:PostReverseFsync, 4:syncPostReverseFsync, 5:PostFsync, 6:syncPostFsync)
.IP
[\-D number (of subdirectories)]
[\-N number (of files in each subdirectory in Round Robin mode)]
[\-d dir1 ... \fB\-d\fR dirN]
[\-l log_file_name]
[\-l log_file_name]
[\-L number (of iterations)]
[\-n number (of files per iteration)]
[\-p number (of total bytes file names)]
[\-r number (of random bytes in file names)]
[\-s byte_count (size in bytes of each file)]
[\-t number (of total threads)]
[\-w number (of bytes per write() syscall)]
.PP
Usage: fs_mark
.HP
\fB\-h\fR <print usage and exit>
.HP
\fB\-k\fR <keep files after each iteration>
.HP
\fB\-F\fR <run until FS full>
.HP
\fB\-S\fR Sync Method (0:No Sync, 1:fsyncBeforeClose, 2:sync/1_fsync, 3:PostReverseFsync, 4:syncPostReverseFsync, 5:PostFsync, 6:syncPostFsync)
.IP
[\-D number (of subdirectories)]
[\-N number (of files in each subdirectory in Round Robin mode)]
[\-d dir1 ... \fB\-d\fR dirN]
[\-l log_file_name]
[\-l log_file_name]
[\-L number (of iterations)]
[\-n number (of files per iteration)]
[\-p number (of total bytes file names)]
[\-r number (of random bytes in file names)]
[\-s byte_count (size in bytes of each file)]
[\-t number (of total threads)]
[\-w number (of bytes per write() syscall)]
.SH "SEE ALSO"
The full documentation for
.B fs_mark:
is maintained as a Texinfo manual.  If the
.B info
and
.B fs_mark:
programs are properly installed at your site, the command
.IP
.B info fs_mark:
.PP
should give you access to the complete manual.
