Document: fsmark
Title: Debian fsmark Manual
Author: <insert document author here>
Abstract: This manual describes what fsmark is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fsmark/fsmark.sgml.gz

Format: postscript
Files: /usr/share/doc/fsmark/fsmark.ps.gz

Format: text
Files: /usr/share/doc/fsmark/fsmark.text.gz

Format: HTML
Index: /usr/share/doc/fsmark/html/index.html
Files: /usr/share/doc/fsmark/html/*.html
